all: primi primi_sequenza sequenze casuali

primi: bin-folder
	g++ primi.cpp -o bin/primi
primi_sequenza: bin-folder
	g++ primi_sequenza.cpp -o bin/primi_sequenza
sequenze: bin-folder
	g++ sequenze.cpp -o bin/sequenze
casuali: bin-folder
	g++ casuali.cpp -o bin/casuali

bin-folder:
	mkdir -p bin

