all: es1 es2 es3 es4 es5 es6

es1: bin-folder
	g++ es1.cpp -o bin/es1
es2: bin-folder
	g++ es2.cpp -o bin/es2
es3: bin-folder
	g++ es3.cpp -o bin/es3
es4: bin-folder
	g++ es4.cpp -o bin/es4
es5: bin-folder
	g++ es5.cpp -o bin/es5
es6: bin-folder
	g++ es6.cpp -o bin/es6

bin-folder:
	mkdir -p bin

